### PR TITLE
Fix #1510

### LINKED ISSUE #1510: CARACal ERROR: KeyError: 'GainDiagAmp'
I am trying to run phase selfcal followed by an amptidue selfcal by setting the following parameter:
gain_matrix_type: ['GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase', 'GainDiagAmp']

However, I get this error:

2023-05-09 15:11:24 CARACal ERROR: 'GainDiagAmp' [KeyError]
2023-05-09 15:11:24 CARACal INFO:   More information can be found in the logfile at output/logs-20230509-151117/log-caracal.txt
2023-05-09 15:11:24 CARACal INFO:   You are running version 1.0.6-2-gd0b9d985
2023-05-09 15:11:24 CARACal ERROR: Traceback (most recent call last):
2023-05-09 15:11:24 CARACal ERROR:   File "/home/stanbury/Software/caracal/caracal/main.py", line 187, in __run
2023-05-09 15:11:24 CARACal ERROR:     pipeline.run_workers()
2023-05-09 15:11:24 CARACal ERROR:   File "/home/stanbury/Software/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
2023-05-09 15:11:24 CARACal ERROR:     worker.worker(self, recipe, config)
2023-05-09 15:11:24 CARACal ERROR:   File "/home/stanbury/Software/caracal/caracal/workers/selfcal_worker.py", line 2155, in worker
2023-05-09 15:11:24 CARACal ERROR:     get_dir_path(image_path, pipeline), mslist, field)
2023-05-09 15:11:24 CARACal ERROR:   File "/home/stanbury/Software/caracal/caracal/workers/selfcal_worker.py", line 1369, in calibrate_cubical
2023-05-09 15:11:24 CARACal ERROR:     "g-type": CUBICAL_MT[matrix_type],
2023-05-09 15:11:24 CARACal ERROR: KeyError: 'GainDiagAmp'
2023-05-09 15:11:24 CARACal INFO: exiting with error code 1

The run completes successfully when I change the gain matrix type to: 
gain_matrix_type: ['GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase', 'GainDiag']

So I am not sure what the KeyError is for GainDiagAmp - any help would be appreciated, please!

### PR DESCRIPTION
**Pull request by KshitijT**
Implementing @o-smirnov and @PeterKamphuis 's suggestion to fix #1510. 

Summary:

Added 
`"GainDiagAmp": 'complex-2x2',`
at line 42 in the selfcal worker.

### CODE REVIEW

**Comment by o-smirnov** [comment]
@Athanaseus or @SpheMakh, looks like flake itself is failing on Python 3.7. But we don't support it anymore so why don't we retire it?

**Comment by KshitijT** [comment]
> Support for `py3.7` was reincorporated in #1498.
> 
> ```
> [tool.poetry.group.tests.dependencies]
> -flake8 = "*"
> +flake8 = "^5.0.0"
> 
> [tool.poetry.group.docs.dependencies]
> -Sphinx = "^5.3.0"
> +Sphinx = "^4.0.1"
> ```
> 
> The following sphinx and flake8 libraries satisfy all the python versions `[3.7, 3.8, 3.9, 3.10]`
> 
> @KshitijT please make the above changes in `pyproject.toml` Then `pip install poetry && poetry lock` to update the lock file of requirements.

@Athanaseus , thanks for the clarification. One quick question, is this already included in the master? Because the branch the PR is based on is fairly new one.

**Comment by Athanaseus** [comment]
> > Support for `py3.7` was reincorporated in #1498.
> > ```
> > [tool.poetry.group.tests.dependencies]
> > -flake8 = "*"
> > +flake8 = "^5.0.0"
> > 
> > [tool.poetry.group.docs.dependencies]
> > -Sphinx = "^5.3.0"
> > +Sphinx = "^4.0.1"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The following sphinx and flake8 libraries satisfy all the python versions `[3.7, 3.8, 3.9, 3.10]`
> > @KshitijT please make the above changes in `pyproject.toml` Then `pip install poetry && poetry lock` to update the lock file of requirements.
> 
> @Athanaseus , thanks for the clarification. One quick question, is this already included in the master? Because the branch the PR is based on is fairly new one.

No, for this reason, the master is not stable within `python3.7`.
You need to make the changes, otherwise I'm happy to make a separate that addresses this and we can merge it, then update this one.

**Comment by KshitijT** [comment]
> > > Support for `py3.7` was reincorporated in #1498.
> > > ```
> > > [tool.poetry.group.tests.dependencies]
> > > -flake8 = "*"
> > > +flake8 = "^5.0.0"
> > > 
> > > [tool.poetry.group.docs.dependencies]
> > > -Sphinx = "^5.3.0"
> > > +Sphinx = "^4.0.1"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The following sphinx and flake8 libraries satisfy all the python versions `[3.7, 3.8, 3.9, 3.10]`
> > > @KshitijT please make the above changes in `pyproject.toml` Then `pip install poetry && poetry lock` to update the lock file of requirements.
> > 
> > 
> > @Athanaseus , thanks for the clarification. One quick question, is this already included in the master? Because the branch the PR is based on is fairly new one.
> 
> No, for this reason, the master is not stable within `python3.7`. You need to make the changes, otherwise I'm happy to make a separate PR that addresses this and we can merge it, then update this one.

Cool, let me make the changes in the PR. I'll mark you as a reviewer on this PR, please check if the changes are satisfactory once I am done.

**Comment by Athanaseus** [comment]
Roger that!

**Comment by Athanaseus** [comment]
`pip install poetry && poetry lock` to update the lock file of requirements.
commit the updated `poetry.lock`

**Comment by Athanaseus** [comment]
Running that command in your development environment should auto-update the https://github.com/caracal-pipeline/caracal/blob/master/poetry.lock file. It would help if you committed that too.

**Comment by Athanaseus** [comment]
@KshitijT please re-check this, I updated the lock file as required.
I also hijacked this PR to update readme (resolves #1519)

**Review by Athanaseus — APPROVED** [review]

**Comment by KshitijT** [comment]
@Athanaseus,  is there something in particular you would like me to check for this PR?

**Comment by Athanaseus** [comment]
@KshitijT No, it's ready for merge.

**Comment by KshitijT** [comment]
> @KshitijT No, it's ready for merge.

Ok, then let's just wait until the checks pass.

**Comment by KshitijT** [comment]
@Athanaseus do we wait for the 3.6-5.7-3.8 builds to go through or they are just stuck and we should just merge?

**Pull request merged**
