### PR TITLE
More and more rope to raise flags with

### PR DESCRIPTION
**Pull request by o-smirnov**
This is likely to cause some arguments, so just flagging it up for now, no pun intended. I still needed #711. So here's my stab at implementing it:
```
  flag_manual:
    enable: true
    rules:
      - '1557* antenna:m007 scan:40'
      - '1557* scan:49'
      - '1568* antenna:m024,m036 scan:35'
```

### CODE REVIEW

**Comment by paoloserra** [comment]
This started as "just" one more way to flag data but I see that there's lots of (unrelated?) changes in this PR. Can we get a very brief description so whoever has time knows what to test?

**Comment by o-smirnov** [comment]
It's only minor tweaks, but because this has the jihad branch merged in too, the diff w.r.t. master looks massive.

I suggest we finish off the jihad and merge it -- then the differences in here will become small again and easy to review.

**Comment by paoloserra** [comment]
I missed that merge -- of course!

**Comment by paoloserra** [comment]
Would you mind removing the two occurrences of `from_target` in https://github.com/caracal-pipeline/caracal/blob/issue-711/caracal/sample_configurations/carateConfig.yml ? Thanks!

**Comment by o-smirnov** [comment]
There, we're back to a sensible diff. So this does two things:

* adds a ``flag: manual`` section which allows for more expressive stuff like:

  ```
  flag_manual:
    enable: true
    rules:
      - '* antenna:S02'             # wild and wooly bandpass
      - '* scan:14~16 antenna:S01'  # phase flip in gaincal scan 15
      - '* antenna:C05&C06;C09&C10;C09&C11;C09&C12;C10&C11;C10&C12;C11&C12'  # big ole fringe on top in 3C147 scan, excess phases in all scans
  ```

* adds am ``inspect: shadems: plot`` section which allows stuff like:

  ```
    plots:
      - '-x real  -y imag   -c SCAN_NUMBER --cnum 100 --col CORRECTED_DATA --iter-field'
      - '-x real  -y imag   -c ANTENNA1 --cnum 100 --col CORRECTED_DATA --iter-field'
      - '-x FREQ -y amp:I -c SCAN_NUMBER --cnum 100 --cmin 0 --cmax 30 --field {bpcal} --dir {msbase}-bpcal-iamp-byant --iter-ant'
      - '-x ANTENNA1 -y ANTENNA2 -a CORRECTED_DATA:amp --ared std --cmap pride --dir {msbase}-stdamp-byscan --iter-scan'
      - '-x ANTENNA1 -y ANTENNA2 -a CORRECTED_DATA:phase --ared std --cmap pride --dir {msbase}-stdphase--byscan --iter-scan'
      - '-x FREQ -y SCAN_NUMBER -a CORRECTED_DATA:amp --ared std --cmap pride --dir {msbase}-stdamp-byant --iter-ant'
      - '-x FREQ -y SCAN_NUMBER -a CORRECTED_DATA:phase --ared std --cmap pride --dir {msbase}-stdphase-byant --iter-ant'
  ```
* makes a small change to the default notebooks to show thumbnails of the plots generated above

**Comment by paoloserra** [comment]
@o-smirnov can the "DO NOT MERGE" label go?

**Comment by o-smirnov** [comment]
Yep, happy to merge it as soon as.

**Pull request merged**
