### PR TITLE
Imcontsub

### PR DESCRIPTION
**Pull request by gigjozsa**
Merges https://github.com/caracal-pipeline/caracal/pull/1426
Implements imcontsub in caracal
Solves #1431
Enables user to use results from imcontsub in sofia in line worker
Example of usage:
[short_contsub_fin.yml.txt](https://github.com/caracal-pipeline/caracal/files/9437916/short_contsub_fin.yml.txt)

### CODE REVIEW

**Comment by gigjozsa** [comment]
Retest this please!

**Comment by gigjozsa** [comment]
@o-smirnov @bennahugo There is no space left on the Jenkins server. I'll have a look if I can fix this, but not very likely.

**Comment by gigjozsa** [comment]
retest this please

**Comment by gigjozsa** [comment]
@o-smirnov @bennahugo Sorry, may I ask for help here? I deleted a few builds, but on the console output I still get no space on device...

**Comment by gigjozsa** [comment]
retest this please

**Comment by paoloserra** [comment]
retest this please

**Comment by paoloserra** [comment]
retest this please

**Comment by paoloserra** [comment]
`polyorder` was not being passed to the function, so the order was always set to the window length. I've now corrected that.

**Comment by paoloserra** [comment]
retest this please

**Review by paoloserra — APPROVED** [review]

**Pull request merged**
