### PR TITLE
typos

### PR DESCRIPTION
**Pull request by gigjozsa**

### CODE REVIEW

**Comment by gigjozsa** [comment]
@paoloserra Like now?

**Comment by svw26** [comment]
Don't merge yet

**Comment by gigjozsa** [comment]
I hear you @svw26

**Comment by svw26** [comment]
Line 282 is now back to where it was before I ever read it, but too late now. I'll fix it ~1 month's time

**Comment by gigjozsa** [comment]
Sigh, sorry. But if this is the only thing left I am actually quite glad. I was pretty shocked when I saw that all these files were merge conflicts.

**Comment by gigjozsa** [comment]
@svw26, there are 10 mins left, my apologies, so for line 282:

```
                desc: Ensure that the selected AOFlagger strategy is compatible with the type of correlations present in the input .MS file(s). E.g., attempts to flag on Stokes V for an .MS with XX and YY only will result in an error and CARACal exiting. The rules are 1. XY,YX must be present in order to flag on Stokes V,U (or on XY,YX), and 2. XX,YY must be present in order to flag on Stokes I,Q (or on XX,YY). Disable this parameter only if you know what you are doing.
```
or
```
                desc: Ensure that the selected AOFlagger strategy is compatible with the type of correlations present in the input .MS file(s). E.g., attempts to flag on Stokes V an .MS with XX and YY only will result in an error and exit Caracal. The rules are 1) XY,YX present to flag on Stokes V,U or on XY,YX, 2) XX,YY present to flag on Stokes I,Q or on XX,YY. Disable only if you know what you are doing.
```

**Comment by svw26** [comment]
I don't want to mess up flag_schema.yml by pushing my own commit, so please just make sure that line 282 uses the following text:

desc: Ensure that the selected AOFlagger strategy is compatible with the type of correlations present in the input .MS file(s). E.g., attempts to flag on Stokes V for an .MS with XX and YY only will result in an error and CARACal exiting. The rules are 1. XY,YX must be present in order to flag on Stokes V,U (or on XY,YX), and 2. XX,YY must be present in order to flag on Stokes I,Q (or on XX,YY). Disable this parameter only if you know what you are doing.

"only thing left" in terms of what I could find in the space of 40 minutes this morning.

**Pull request merged**
