### PR TITLE
make dist-max-chunks harmless again + divide & conquer + auto uvlin selection

### PR DESCRIPTION
**Pull request by paoloserra**
This PR groups together a bunch of changes we're using when reducing the Fornax data at ILIFU, which should be of general interest.

- When _transferring_ the selfcal gains, take dist-max-chunks from `cal_cubical: dist_max_chunks`. In current master it is hardcoded to 0, which can cause memory errors.  This is discussed at https://github.com/caracal-pipeline/caracal/issues/1198 . We haven't converged on a final solution yet, and there are new versions of Cubical coming up, but at least the change in this PR does away with the hardcoded value of 0 in master, and gives users control.

- Add a new mode of the `transform` worker, where `label_in` can be a list of comma-separated values, each associated to a target-only MS covering a certain frequency range. In this case, for each input MS and target, `transform` can be asked to concatenate all MS files along the frequency axis. It is assumed that the concatenation makes sense (i.e., the frequency ranges are contiguous). This mode enables a multi-node workflow where the target is initially split from a wide-band MS into N MS files (one per available node), each taking a portion of the band; then these files are flagged and frequency-averaged in prep for continuum imaging and selfcalibration (again one per node, which is faster than doing this on a single node for the full band); finally, before running `selfcal`, the files are concatenated back into a wide-band, freq-averaged MS (to allow, e.g., freq-independent gains). Obviously, this mode is optional and, at this point, somewhat experimental -- but it's proven useful for processing the Fornax data on ILIFU. All defaults have been set such that normally this mode is disabled and everything works as it used to.

- As usual, users can select the channels to be included in the UVLIN fit in `line: mstransform`. Here we add the possibility of automatically excluding from the fit channels hosting known bright line sources. The way to do this is explained in the schema file of the `line` worker. The automated selection is combined with the user selection before running UVLIN. I've included the HIPASS catlaogue as well as a Fornax-specific HI catalogue, but users can put their own catalogue in pipeline.input as long as it follows the format described in the schema.

### CODE REVIEW

**Comment by KshitijT** [comment]
Poitnts 1 and 3 tested and seem to work.
P.S. @paoloserra , it would be good to list the known HI source catalogues already pre-packaged by name with CARACal (e.g. HIPASS), for the convenience of the user.

**Comment by KshitijT** [comment]
@paoloserra , I get the following error while testing this PR:
```
 --> CrashReporter initialized.
# 2020-10-11 14:54:46   INFO    concat::::
# 2020-10-11 14:54:46   INFO    concat::::+     ##########################################
# 2020-10-11 14:54:46   INFO    concat::::+     ##### Begin Task: concat             #####
# 2020-10-11 14:54:46   INFO    concat::::      concat(vis=['/stimela_mount/msdir/X-avg-J2018_5539-hi.ms', '/stimela_mount/msdir/X-avg-J2018_5539-lo.ms'],concatvis="/stimela_mount/msdir/tobedeleted-X-avg-J2018_5539-corr.ms",freqtol="",dirtol="",respectname=False,
# 2020-10-11 14:54:46   INFO    concat::::+             timesort=False,copypointing=True,visweightscale=[],forcesingleephemfield="")
# 2020-10-11 14:54:46   INFO    concat::::      copying /stimela_mount/msdir/X-avg-J2018_5539-hi.ms to /stimela_mount/msdir/tobedeleted-X-avg-J2018_5539-corr.ms
# 2020-10-11 14:54:52   INFO    concat::::      concatenating /stimela_mount/msdir/X-avg-J2018_5539-lo.ms into /stimela_mount/msdir/tobedeleted-X-avg-J2018_5539-corr.ms
# 2020-10-11 14:54:52   SEVERE  ms::concatenate Exception Reported: Table column SIGMA_SPECTRUM is unknown
# *** Error *** Table column SIGMA_SPECTRUM is unknown
# 2020-10-11 14:54:52   SEVERE  concat::::      An error occurred running task concat.
# Running CASA task 'concat'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 8, in <module>
#     task.run()
#   File "/usr/local/lib/python3.6/dist-packages/Crasa/Crasa.py", line 122, in run
#     raise CasaException("CASA raised a SEVERE exception while running task {0:s}".format(self.task))
# Crasa.Crasa.CasaException: CASA raised a SEVERE exception while running task concat
2020-10-11 14:54:55 CARACal.Stimela.concat-ms0-0 ERROR: docker returns error code 1
2020-10-11 14:54:55 CARACal.Stimela.concat-ms0-0 ERROR: job failed at 2020-10-11 14:54:55.521310 after 0:00:14.368288
2020-10-11 14:54:55 CARACal ERROR: Job 'concat-ms0-0:: Concatenate ['X-avg-J2018_5539-hi.ms', 'X-avg-J2018_5539-lo.ms']' failed: docker returns error code 1 [PipelineException]
2020-10-11 14:54:55 CARACal INFO:   More information can be found in the logfile at concat/logs-20201011-145427/log-caracal.txt
2020-10-11 14:54:55 CARACal INFO: exiting with error code 1
```

**Context**: I was a bit confused about point 2 (concat) above; finally ran the pipeline twice to generate 'lo' and 'hi' datasets for different, but contiguous channel ranges. Then ran the following iteration of `transform`:

```
transform__2:
  enable: true
  label_in: hi,lo
  split_field:
    enable: false
    otfcal:
      enable: false
      label_cal: '1gc1'
  concat:
    enable: true
```
which gives the above error.

Could you please point out what am I missing here?

**Comment by paoloserra** [comment]
Please tell me what's confusing.

Anyway, I don't think you're missing anything. However, your MS files seem to be missing the SIGMA_SPECTRUM column. I have no clue why that'd be a problem though.

I guess we've always had that column in our tests so far, though I'm not sure why.

**Comment by KshitijT** [comment]
> Please tell me what's confusing.
> 
> Anyway, I don't think you're missing anything. However, your MS files seem to be missing the SIGMA_SPECTRUM column. I have no clue why that'd be a problem though.
> 
> I guess we've always had that column in our tests so far, though I'm not sure why.

Yes, I had put the same measurement set through standard pipeline and had no issues (case in point, the "lo" and "hi" measurement sets); so certainly weird why this happens. Maybe it's just a peculiarity of the measurement set I am using; since yours go through fine. As the `concat` mode is experimental right now, I think I'll stop digging here and approve the PR; but maybe we want to add the reverse capability too at some point? Splitting the measurement set with `label_out` taking a comma separated list with each label corresponding to a separate spw ?

**Review by KshitijT — DISMISSED** [review]

**Comment by paoloserra** [comment]
Can the `prep` worker be used to add a SIGMA_SPECTRUM? If so, would you  be willing to test whether doing that solves your problem? You're right, it's experimental, but it'd be nice to know there's a solution to this.

I've seen your suggestion on the HI catalogues, it's a good one, I'll make the change in this PR.

**Comment by KshitijT** [comment]
> Can the prep worker be used to add a SIGMA_SPECTRUM? If so, would you be willing to test whether doing that solves your problem? You're right, it's experimental, but it'd be nice to know there's a solution to this.

I'll check that out, just finishing the changes requested by @o-smirnov for #1254 first, I hope that's ok?

**Comment by paoloserra** [comment]
no rush whatsoever mate

**Comment by KshitijT** [comment]
Great, seems to work fine now - might have been an issue with my config settings earlier.

Sorry to be a pest about this, but one error which I still get is if the SPWs in the pre-concatenated measurement sets are of different lengths (i.e. 100 channels in 1 and 101 channels in the other). 

@paoloserra : could you please: 1) confirm if that's what you see 2) if true, then add a warning in the schema about this for the concat keyword ? Also that the channel ranges need to be contiguous.

**Comment by paoloserra** [comment]
@KshitijT Are the two ranges are contiguous in the 100+101 chans case? What's the error?

**Comment by KshitijT** [comment]
> @KshitijT Are the two ranges are contiguous in the 100+101 chans case? What's the error?

Yup, they were contiguous. The error comes when trying to transform the concatenated (tobedeleted) MS to the final one - `combinespws`,  which is ON by default, complains about the spw lengths not being the same - one having 100 channels and the other having 101 channels.

**Comment by paoloserra** [comment]
That's too bad. There's not much we can do unfortunately, see the note on `combinespws` at https://casa.nrao.edu/casadocs/casa-5.3.0/global-task-list/task_mstransform/about .

I'll add the warning in the schema as you suggested.

When  I commit that change I'll also add the scan selection when splitting. I'm finding that useful, and you had also requested that  in #1163 .

I also need to run some sanity check on the  new UVLIN catalogue functionality. I  got some strange results over the weekend and need to check. In the meantime I'm of course happy if you can  review the changes which I'll commit in a few minutes.

**Comment by KshitijT** [comment]
> That's too bad. There's not much we can do unfortunately, see the note on `combinespws` at https://casa.nrao.edu/casadocs/casa-5.3.0/global-task-list/task_mstransform/about .
> 
> I'll add the warning in the schema as you suggested.
> 
> When I commit that change I'll also add the scan selection when splitting. I'm finding that useful, and you had also requested that in #1163 .
> 
> I also need to run some sanity check on the new UVLIN catalogue functionality. I got some strange results over the weekend and need to check. In the meantime I'm of course happy if you can review the changes which I'll commit in a few minutes.

Sure, I think @gigjozsa also wants to review the PR separately anyway.

**Comment by paoloserra** [comment]
@KshitijT @gigjozsa all good on my side. There were no bugs -- or rather the only bugs were in my head, the code was fine.

**Comment by paoloserra** [comment]
ok to test

**Comment by paoloserra** [comment]
ok to test

**Review by KshitijT — APPROVED** [review]
Ok to test.

**Pull request merged**
