### PR TITLE
Refactoring the Inspect worker

### PR DESCRIPTION
**Pull request by Mulan-94**
- An attempt at refactoring the inspect worker
- Removes `gaintype` argument from crosscal `plotgains()`

### CODE REVIEW

**Comment by KshitijT** [comment]
@Mulan-94 , could you please level the PR with master branch and maybe suggest a configuration setting to test it out?

**Comment by KshitijT** [comment]
I get the following error when testing this PR:
```
2020-10-18 13:26:08 CARACal.Stimela.inspect INFO: Config directory cannot be found. Will create /data2/kshitij/caracal_tests/.stimela_workdir-1603027568266093/stimela_parameter_files
2020-10-18 13:26:08 CARACal INFO: inspect: initializing
2020-10-18 13:26:08 CARACal INFO: Plotting MS: 1524929477-cal.ms
2020-10-18 13:26:08 CARACal WARNING: The shadems section is enabled, but doesn't specify any plot_by_field or plot_by_corr or plots
2020-10-18 13:26:08 CARACal ERROR: 'colour' [KeyError]
2020-10-18 13:26:08 CARACal INFO:   More information can be found in the logfile at output_refactor/logs-20201018-131647/log-caracal.txt
2020-10-18 13:26:08 CARACal INFO:   You are running version v1.0.3-208-g218351d4
2020-10-18 13:26:08 CARACal ERROR: Traceback (most recent call last):
2020-10-18 13:26:08 CARACal ERROR:   File "/data2/kshitij/caracal/caracal/main.py", line 183, in __run
2020-10-18 13:26:08 CARACal ERROR:     pipeline.run_workers()
2020-10-18 13:26:08 CARACal ERROR:   File "/data2/kshitij/caracal/caracal/workers/worker_administrator.py", line 397, in run_workers
2020-10-18 13:26:08 CARACal ERROR:     worker.worker(self, recipe, config)
2020-10-18 13:26:08 CARACal ERROR:   File "/data2/kshitij/caracal/caracal/workers/inspect_worker.py", line 589, in worker
2020-10-18 13:26:08 CARACal ERROR:     extras=None)
2020-10-18 13:26:08 CARACal ERROR:   File "/data2/kshitij/caracal/caracal/workers/inspect_worker.py", line 470, in ragavi_vis
2020-10-18 13:26:08 CARACal ERROR:     "colour-axis": basic["colour"],
2020-10-18 13:26:08 CARACal ERROR: KeyError: 'colour'
2020-10-18 13:26:08 CARACal INFO: exiting with error code 1
```
@Mulan-94 , could you please take a look ?
The `inspect` section I am using in the config file is pretty much vanilla and looks like:
```
inspect:
  enable: true
  label_in: 'cal'
  label_plot: '1gc'
  field: 'calibrators'
  real_imag:
    enable: true
    avgtime: '60'
  amp_phase:
    enable: true
    avgtime: '60'
  amp_uvwave:
    enable: true
    avgtime: '60'
  amp_ant:
    enable: true
    avgtime: '60'
  phase_uvwave:
    enable: true
    avgtime: '60'
  amp_scan:
    enable: true
    avgtime: '60'

```

**Comment by Mulan-94** [comment]
On it.

**Comment by KshitijT** [comment]
> On it.

Thanks, @Mulan-94 .

**Comment by Mulan-94** [comment]
Ok @KshitijT, I tihnk this has been fixed now and is ready for testing again. Sorry for the delay.

**Comment by KshitijT** [comment]
> Ok @KshitijT, I tihnk this has been fixed now and is ready for testing again. Sorry for the delay.

What delay? :)
Thanks so much for a very quick response, I'll re-test this.

**Comment by KshitijT** [comment]
I am encountering another error now, @Mulan-94 :

```
2020-10-20 08:20:17 CARACal INFO: inspect: running
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 INFO: job started at 2020-10-20 08:20:17.393717
2020-10-20 08:20:17 CARACal.Stimela.inspect INFO: STEP 1 :: 1gc
2020-10-20 08:20:17 CARACal.Stimela INFO: Validating parameters for cab ragavi (stimela/ragavi:1.7.2)
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR: Parameter 'yaxis', can only be either of ['amplitude', 'imaginary', 'phase', 'real']
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR: job failed at 2020-10-20 08:20:17.394060 after 0:00:00.000343
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR: Traceback (most recent call last):
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 704, in run
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:     job.run_job()
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 415, in run_job
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:     self.job.parameter_file_name, tag=self.tag)
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:   File "/data2/kshitij/Stimela/stimela/cargo/cab/__init__.py", line 381, in update
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:     param.validate(value)
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:   File "/data2/kshitij/Stimela/stimela/cargo/cab/__init__.py", line 83, in validate
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR:     self.name, self.choices))
2020-10-20 08:20:17 CARACal.Stimela.plot-amp_ant-0-4 ERROR: stimela.exceptions.StimelaCabParameterError: Parameter 'yaxis', can only be either of ['amplitude', 'imaginary', 'phase', 'real']
2020-10-20 08:20:17 CARACal.Stimela.inspect INFO: Completed jobs : []
2020-10-20 08:20:17 CARACal.Stimela.inspect INFO: Remaining jobs : ['plot-amp_ant-0-0', 'plot-amp_ant-0-3', 'plot-amp_phase-0-4', 'plot-amp_phase-0-0', 'plot-amp_phase-0-3', 'plot-amp_scan-0-4', 'plot-amp_scan-0-0', 'plot-amp_scan-0-3', 'plot-amp_uvwave-0-4', 'plot-amp_uvwave-0-0', 'plot-amp_uvwave-0-3', 'plot-phase_uvwave-0-4', 'plot-phase_uvwave-0-0', 'plot-phase_uvwave-0-3', 'plot-real_imag-0-4', 'plot-real_imag-0-0', 'plot-real_imag-0-3']
```

**Comment by Mulan-94** [comment]
Hey @KshitijT , yeah this is because of `Stimela`, there are some changes I had made to `ragavi`. This is my branch with the changes: 
 `https://github.com/Mulan-94/Stimela.git@update_ragavi`

**Comment by KshitijT** [comment]
Oh, are the changes not in Stimela master then?

**Comment by Mulan-94** [comment]
> Oh, are the changes not in Stimela master then?

Yeah not yet

**Comment by o-smirnov** [comment]
The new Stimela release has the required changes, so:

restest this please

(Does jenkins recognize commands embedded within a comment?)

**Comment by o-smirnov** [comment]
retest this please

**Comment by o-smirnov** [comment]
Tests pass. But perhaps I should merge this with #1262, and test the two together? Seeing as they both relate to plotting.

**Comment by o-smirnov** [comment]
I've merged this branch into #1262, so if you make no further changes, this will go in together with that PR. I'm therefore closing this PR.

**Pull request closed without merging**
