### PR TITLE
1462 regrid mask sneakily fails

### PR DESCRIPTION
**Pull request by Fil8**
I checked and now mask is not regridded if not needed

### CODE REVIEW

**Comment by SpheMakh** [comment]
Okay to test

**Review by SpheMakh — DISMISSED** [review]

**Comment by SpheMakh** [comment]
Okay to test

**Comment by Athanaseus** [comment]
ok to test

**Comment by Athanaseus** [comment]
retest this please

**Review by SpheMakh — DISMISSED** [review]

**Comment by paoloserra** [comment]
@Fil8 I'm testing the change related to #1468 and it does not seem to be working. I suggest you remove this change from this PR, so we do not block it, and I make a separate branch and a separate PR to fix #1468.

**Comment by paoloserra** [comment]
@Fil8 this is probably me having issues installing caracal because of being on an old python version, but still, let's decouple this PR from #1468

**Review by SpheMakh — APPROVED** [review]

**Pull request merged**
