### PR TITLE
Blind debugging

### PR DESCRIPTION
**Pull request by KshitijT**
Updating the pip update command for tests to go smoothly.

### CODE REVIEW

**Comment by Athanaseus** [comment]
@KshitijT I had a chat with @bennahugo relating this. The lists of licenses are no longer supported by `pip`.

In setup.py:
```
License=["GNU GPL v2"]
```
must be
```
License="GNU GPL v2"
```

**Comment by KshitijT** [comment]
> @KshitijT I had a chat with @bennahugo relating this. The lists of licenses are no longer supported by `pip`.
> 
> In setup.py:
> 
> ```
> License=["GNU GPL v2"]
> ```
> 
> must be
> 
> ```
> License="GNU GPL v2"
> ```

Cool, let me try out and then we can pass this PR, so that other PRs aren't halted because of failing test when they level with master.

**Comment by KshitijT** [comment]
@Athanaseus , can has review?

**Review by Athanaseus — APPROVED** [review]

**Comment by o-smirnov** [comment]
ok to test

**Comment by KshitijT** [comment]
@bennahugo, @o-smirnov  any idea why the final build check is failing?

**Comment by KshitijT** [comment]
retest this please

**Pull request merged**
