### PR TITLE
Inflationary jihad in support of R/O MS workflows

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by gigjozsa** [comment]
ok to test

**Comment by SpheMakh** [comment]
@gigjozsa can you assist in getting this branch compatible with the carate kit. The major change is that the input (raw) MS does not have to be in the same folder as the ones produced by the pipeline, in fact, it recommended that it is not. So the `general`  has been updated to be 

```
general:
  rawdatadir: <raw data folder>
  msdir: <output MS folder>
```

**Comment by gigjozsa** [comment]
I stopped the Jenkins test. Will merge with #1162 and restart once #1162 has gone through.

**Comment by o-smirnov** [comment]
@paoloserra this passes the standard tests now. Ready for you to test. But please note it needs this Stimela branch: https://github.com/ratt-ru/Stimela/pull/643.

So harass @SpheMakh v1.1.0 to merge the PR, or just test against the branch for now.

**Comment by paoloserra** [comment]
Is this supposed to work with python 3.5? That's still our requirement. We do not require 3.6.

For example, the following line gives problems

https://github.com/caracal-pipeline/caracal/blob/a255983c4654f1cf3402a208aef9b1e4fe7986a1/caracal/workers/prep_worker.py#L23

**Comment by o-smirnov** [comment]
OK, pull again.

Somebody forgot to add ``# -*- coding: future_fstrings -*-`` at the top before deploying f-strings.

**Comment by paoloserra** [comment]
obsinfo files and elevation tracks are created  both in msdir and output/obsinfo

**Comment by o-smirnov** [comment]
Yeah that's intentional. They had to go into msdir (see discussion on slack), but I make a courtesy copy into output to make the reports complete.

**Comment by paoloserra** [comment]
I guess I missed that (or forgot). Could you point  me to it?

**Comment by o-smirnov** [comment]
Actually not on Slack I see, but rather the problem (with keeping them in output) was raised in this comment: https://github.com/caracal-pipeline/caracal/issues/1170#issuecomment-641489172

I was then seconded by @SpheMakh in an offline discussion, so I implemented the msdir approach on the branch.

**Comment by o-smirnov** [comment]
Just a heads-up, I'm going to merge ``issue-1173`` into this, as it passes standard tests. This is just part of the MS extension cleanup jihad, no functional changes. But you may as well test with it merged in.

**Comment by paoloserra** [comment]
I see. Apologies for missing that.

But if you wanted to compare output  products obtained with different settings  why  didn't you  just  change `general: prefix`? Isn't that  the  entire point of that parameter? You  don't need multiple output directories.

**Comment by paoloserra** [comment]
> Just a heads-up, I'm going to merge `issue-1173` into this, as it passes standard tests. This is just part of the MS extension cleanup jihad, no functional changes. But you may as well test with it merged in.

OK. Please note I've committed some minor changes here.

**Comment by o-smirnov** [comment]
> Isn't that the entire point of that parameter? You don't need multiple output directories.

Yep, I guess that would be another way to do it. I find multiple output dirs more convenient, but that's just me.

My funny use case notwithstanding, keeping obsinfo in output means you can never skip a transform step with a new output directory. That seems limiting (and is not explicitly documented, is it?) Furthermore, we argued on the issue that split MSs should not have prefixes. Therefore, obsinfo files should not have prefixes either. So they belong with the MS, both in spirit and in body.

**Comment by paoloserra** [comment]
OK, I'll just get used to it. No  big deal.

**Comment by paoloserra** [comment]
A (hopefully positive) note: I've tried to run this branch on some msfiles located in a read/execute-only directory and it worked. The full directory was `dr-xr-xr-x` (done with `chmod 555`). The `execute` bit is required. @o-smirnov please confirm that  this is what we're aiming for.

**Comment by o-smirnov** [comment]
Exactly what we're aiming for. Rawdatadir should stay virginal and unsullied.

**Comment by paoloserra** [comment]
what is the new parameter `transform: from_target` for?

**Comment by o-smirnov** [comment]
Is it new? @SpheMakh must've added it.

Looking at the code, it's for transforming split-out target MSs.

**Comment by paoloserra** [comment]
but that was already  taken care of by `label_in`

**Comment by o-smirnov** [comment]
So the problem is, is you're transforming a target, then there are potentially multiple per-target MSs per each original MS, right? The transform worker needs to know that this is the case so it can loop over them. So how does it know that it's dealing with targets? We can bake in the logic that ``label_in == "corr"`` implies target, but then we should take away the flexibility of specifying this as ``label_out`` in the originating transform worker, because any value other than "corr" will break the pipeline.

I guess what I'm saying is that if ``label_in`` and ``label_out`` have meaning to the pipeline (as opposed to being free-form labels), then we need to enforce this in the schema.

**Comment by paoloserra** [comment]
This was already  taken care of. When `label_in` is not empty, if `split_field: field: target` then `transform` loops over all .MS files <basename>-<target_name>_<label_in>.ms (one per target per input .MS).

**Comment by o-smirnov** [comment]
Ah ok. Well this is why good comments are important. :)

The original logic was not clear from the code. The @SpheMakh went in and made changes in support of the R/O workflow, breaking the logic in the process (Sphe, I think you introduced from_target at this point?). Then I went in and cleaned up, and here we are, contemplating this one-eyed mutant with a testicle where the ear out to be.

Even if we fix it, it is still problematic. What if ``split_field`` is disabled, but ``changecentre`` isn't? Which field do we change the phase centre of? Must the operation of ``changecentre`` predicate on a  parameter specified in another subsection of the config? I think this argues for a top-level ``field`` parameter. 

Also, I think ``obsinfo`` should not be configurable here. If we make a new MS, we must generate an obsinfo/summary for it, period -- the pipeline cannot function without a matching obsinfo for every MS, so why allow the user to switch it off? (We don't allow switching off the initial obsinfo generation...)

**Comment by paoloserra** [comment]
yeah, we could move `transform: split_field: field` to `transform: field`. That is the same logic used in the `prep` and `flag` workers.

**Comment by paoloserra** [comment]
on this branch and with Stimela master I get perl warnings with CASA fluxscale in crosscal

**Comment by paoloserra** [comment]
It would be nice if we primnted the MS name before summarising its targets, calibrators etc. The current output is not very clear. See example below for 3 input .MS files.

```
2020-06-12 17:31:18 CARACal INFO: obsconf: initializing
2020-06-12 17:31:18 CARACal INFO: obsinfo file gps1-obsinfo.txt exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: summary file gps1-summary.json exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: elevation plot gps1-elevation-tracks.png exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: obsinfo file gps3-obsinfo.txt exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: summary file gps3-summary.json exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: elevation plot gps3-elevation-tracks.png exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: obsinfo file gps2-obsinfo.txt exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: summary file gps2-summary.json exists, not regenerating
2020-06-12 17:31:18 CARACal INFO: elevation plot gps2-elevation-tracks.png exists, not regenerating
2020-06-12 17:31:19 CARACal INFO: MS has 1 spectral windows, with NCHAN=100
2020-06-12 17:31:19 CARACal INFO: CHAN_FREQ from 1391626953.125 Hz to 1412316406.25 Hz with average channel width of 208984.375 Hz
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: TARGET
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: T29R03C01 (ID=2) : 54.78 minutes | RA=142.50 deg, Dec=-52.60 deg
2020-06-12 17:31:19 CARACal INFO: T29R03C03 (ID=3) : 52.91 minutes | RA=141.33 deg, Dec=-51.91 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_AMPL,CALIBRATE_PHASE
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0825-5010 (ID=1) : 15.19 minutes | RA=126.36 deg, Dec=-50.18 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_FLUX
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_BANDPASS
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: MS has 1 spectral windows, with NCHAN=100
2020-06-12 17:31:19 CARACal INFO: CHAN_FREQ from 1391626953.125 Hz to 1412316406.25 Hz with average channel width of 208984.375 Hz
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: TARGET
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: T29R03C01 (ID=2) : 54.78 minutes | RA=142.50 deg, Dec=-52.60 deg
2020-06-12 17:31:19 CARACal INFO: T29R04C02 (ID=3) : 52.24 minutes | RA=141.35 deg, Dec=-52.61 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_AMPL,CALIBRATE_PHASE
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0825-5010 (ID=1) : 15.19 minutes | RA=126.36 deg, Dec=-50.18 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_FLUX
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_BANDPASS
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: MS has 1 spectral windows, with NCHAN=100
2020-06-12 17:31:19 CARACal INFO: CHAN_FREQ from 1391626953.125 Hz to 1412316406.25 Hz with average channel width of 208984.375 Hz
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: TARGET
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: T29R03C05 (ID=2) : 52.38 minutes | RA=140.20 deg, Dec=-51.22 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_AMPL,CALIBRATE_PHASE
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0825-5010 (ID=1) : 15.19 minutes | RA=126.36 deg, Dec=-50.18 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_FLUX
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: ====================================
2020-06-12 17:31:19 CARACal INFO: CALIBRATE_BANDPASS
2020-06-12 17:31:19 CARACal INFO:  ---------------------------------- 
2020-06-12 17:31:19 CARACal INFO: J0408-6545 (ID=0) : 14.26 minutes | RA=62.08 deg, Dec=-65.75 deg
2020-06-12 17:31:19 CARACal INFO: obsconf: running
2020-06-12 17:31:19 CARACal INFO: obsconf: finished
```

**Comment by o-smirnov** [comment]
Your wish is my command. Not a fan of the ASCII art anyway.

> on this branch and with Stimela master I get perl warnings with CASA fluxscale in crosscal

Aha! @SpheMakh take note. This must be the mystery perl I spotted earlier.

**Comment by paoloserra** [comment]
This worked for me (didn't test the last commit though).

I think based on the  comments above there will be a few changes before merging, in particular https://github.com/caracal-pipeline/caracal/pull/1152#issuecomment-643223440.

Happy to test again when needed (if you can wait until Wed when I'm back.)

**Comment by o-smirnov** [comment]
Yeah no rush, this is definitely R1.1 territory. Thanks for the testing and enjoy your break!

**Comment by paoloserra** [comment]
@o-smirnov can we try to finalize this one? Do you need any help from me?

**Comment by o-smirnov** [comment]
I think only the small change in https://github.com/caracal-pipeline/caracal/pull/1152#issuecomment-643223440 still needs to be done. You want to do the honours, or shall I?

Otherwise this looks good to go to me. Someone needs to review and approve, and @SpheMakh needs to push a new Stimela release for this to work.

**Comment by gigjozsa** [comment]
@o-smirnov note that if this goes through with the Jenkins test, we are not really testing R/O yet.

**Comment by paoloserra** [comment]
I need to look at it again, but sure, I can make that change in the coming days.

@gigjozsa The R/O aspect was already tested by me, it works. See comments above.

**Comment by paoloserra** [comment]
@o-smirnov I think that this does what we've discussed. Please have a look.

**Comment by o-smirnov** [comment]
@paoloserra looks correct to me.

**Comment by paoloserra** [comment]
OK, are we done with this then? If so could you approve? And I think you also need to trigger the test.

**Comment by paoloserra** [comment]
Can somebody with access to RARG Jenkins please check what's up?

**Comment by gigjozsa** [comment]
Jenkins is currently running to test #1175 and I believe this one is next in queue.

**Comment by gigjozsa** [comment]
@paoloserra Jenkins finished also for this. Again, the fact that the Jenkins test has passed does not mean that the R/O workflow has been tested. Could you please update me on the syntax that you have settled on? With a lot of the discussion happening elsewhere I lost the thread.

**Comment by o-smirnov** [comment]
@gigjozsa I propose we merge and let the testing catch up. The R/O workflow option is not supposed to disturb older workflows, and the fact that current tests pass makes us reasonably sure that indeed it doesn't. The R/O workflow itself has been reasonably well tested outside of caratekit by both @paoloserra and me. So ~**Ber-nie! Ber...**~ **MERGE! MERGE!** but we can vote at the meeting tomorrow.

The syntax is very simple, you specify the directory of the original MS in ``general: rawdatadir:``, and the rest takes care of itself. For extra testing purity, you might want to ``chmod -R a-w`` the original MSs, just to keep our sacred read-only intentions honest and pure.

**Comment by gigjozsa** [comment]
What actually happens if you specify msdir and rawdatadir to be the same?

**Comment by o-smirnov** [comment]
Try it. I don't see why it wouldn't work. The split-out MSs all have label suffixes on them, so there shouldn't be any name clashes.

**Comment by gigjozsa** [comment]
Will in fact rewrite the test tomorrow first thing and potentially also test the above. Let us discuss tomorrow if the documentation is up-to-date. I am just impressed by the many changes...

**Comment by paoloserra** [comment]
@gigjozsa as mentioned in this discussion above, I've tested that R/O works by running the pipeline on R/O files located in a R/O directory. I'm not sure what more I can do about this.

Concerning readthedocs, all CARACal's stable releases are in there. The latest update of readthedocs to CARACal's master is from 17 Jun, so it currently misses 3 commits (all from you -- and all related to caratekit).

Before merging this branch I'll check that  `rawdatadir` is described properly in the schema.

**Comment by paoloserra** [comment]
@gigjozsa please have a look at the change in `general_schema`. 

Note that  https://caracal.readthedocs.io/en/latest/manual/reduction/prepare/index.html will also need to  be updated, but I will only do it once this  PR is merged into master.

**Comment by o-smirnov** [comment]
@paoloserra, while the transform worker is still fresh in your ~haem~ head, let me remind you of this remark of mine:

> Also, I think obsinfo should not be configurable here. If we make a new MS, we must generate an obsinfo/summary for it, period -- the pipeline cannot function without a matching obsinfo for every MS, so why allow the user to switch it off? (We don't allow switching off the initial obsinfo generation...)

So, can we hardwire the summary/obsinfo generation to always-on? I fully believe in giving the user rope, but this seems like a "make pipeline fall on its face: yes/no?" option...

**Comment by paoloserra** [comment]
Fine with me. And in this case I would run it even if the obsinfo files already exist, consistently with the fact that transform overwrites splitted MS files.

**Comment by o-smirnov** [comment]
Yes exactly, a new MS written (or rephased) means we are morally obligated
to regenerate them.

**Pull request merged**
