### PR TITLE
Fixes pyregions error

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by o-smirnov** [comment]
Cool -- I need to apply the same fix to radiopadre. So the secret sauce is just ``numpy>=1.14``, right?

Are the changes to caratekit's configs intentional?

**Comment by SpheMakh** [comment]
> Cool -- I need to apply the same fix to radiopadre. So the secret sauce is just `numpy>=1.14`, right?
> 
> Are the changes to caratekit's configs intentional?

Yeah, those parameters should be set on the command line for the test jobs as needed. 

```
caracal -c <config> --getdata-dataid <dataid> --obsconf-refant m010 
```

@gigjozsa can we make this change to the carate kit so that the sample configs don't have data specific defaults

**Comment by SpheMakh** [comment]
ok to test

**Comment by KshitijT** [comment]
Hold on, my ddcal test is still running.

**Comment by KshitijT** [comment]
@SpheMakh , if you are happy with this, could you merge the PR?

**Pull request merged**
