### PR TITLE
Issues 1233 1252 1219 1208

### PR DESCRIPTION
**Pull request by o-smirnov**
This clears my R1.0.4 deck.

### CODE REVIEW

**Comment by o-smirnov** [comment]
ok to test

**Comment by o-smirnov** [comment]
ok to test

**Comment by o-smirnov** [comment]
ok to test

**Comment by KshitijT** [comment]
@o-smirnov , this branch is out of date with master, could you please update it?

**Comment by o-smirnov** [comment]
Done. Did you not have the power?

**Comment by KshitijT** [comment]
> Done. Did you not have the power?

I do - but this is a rather complicated PR - didn't want to accidentally break it.

**Comment by o-smirnov** [comment]
Well I just pushed the button and damn the torpedoes! That's for the reviewers to worry about...

**Comment by KshitijT** [comment]
> Well I just pushed the button and damn the torpedoes! That's for the reviewers to worry about...

image

**Comment by o-smirnov** [comment]
Start integration test on Alderaan?..

**Comment by KshitijT** [comment]
> Start integration test on Alderaan?..

"Where's Alderaan?"
"Exactly !"

**Comment by o-smirnov** [comment]
What's was that's laser beam's FWHM again?..

**Comment by KshitijT** [comment]
> What's was that laser beam's FWHM again?..

Just big enough so that Azrael fits on its tip.

**Comment by o-smirnov** [comment]
But the calibrator was offset by 2''!

**Comment by KshitijT** [comment]
> But the calibrator was offset by 2''!

Fixed by #1254.

**Comment by o-smirnov** [comment]
> Fixed by #1254

ok to test

**Comment by o-smirnov** [comment]
Tests pass. Planet, what planet? Can has approve please?

**Comment by KshitijT** [comment]
> Tests pass. Planet, what planet? Can has approve please?

My tests are still running, Governor ! The superlaser recharging time has increased somewhat.

**Comment by o-smirnov** [comment]
What conflict-seeking rebel scum has done *this*? :angry:

**Comment by KshitijT** [comment]
> What conflict-seeking rebel scum has done _this_?

Erm. @KshitijT has been seen waving lightsabers around. Probably him.

**Comment by o-smirnov** [comment]
Well he can go and resolve the conflicts then. You lot in funny robes were supposed to be the peacekeeping force, right?

**Comment by KshitijT** [comment]
> Well he can go and resolve the conflicts then. You lot in funny robes were supposed to be the peacekeeping force, right?

Si vis pacem, para bellum. :P

**Comment by o-smirnov** [comment]
Praise the Lord and pass the ammunition?

**Comment by KshitijT** [comment]
> Praise the Lord and pass the ammunition?

I want to quickly check ddcal worker which I am sure the standard tests don't check; since this PR addresses #1219 .

**Comment by KshitijT** [comment]
This PR runs fine, but wasn't able to run ddcal worker since that needs to be fixed separately. 

Powers-that-be, please don't do a Born Free on CARACal before I fix the ddcal worker (shouldn't take more than a day, sorry).

**Review by KshitijT — APPROVED** [review]

**Comment by paoloserra** [comment]
ok to test

**Comment by o-smirnov** [comment]
Finally!

**Pull request merged**
