### PR TITLE
Parallel gridding

### PR DESCRIPTION
**Pull request by Athanaseus**

### CODE REVIEW

**Review by SpheMakh — CHANGES_REQUESTED** [review]
Please sync the poetry.lock file with master

**Comment by Athanaseus** [comment]
@paoloserra 

The default gridder in `WSClean`  is the `w-stacking` gridder (fast for up to about 5k images), in particular when it can be combined with the `-parallel-gridding` option.

When parallel gridding is not possible, or when image sizes are reasonably large, the [w-gridder](https://wsclean.readthedocs.io/en/latest/wgridding.html) might be a better choice.

Therefore, this will be enabled by the `use_wgridder` switch.

https://wsclean.readthedocs.io/en/latest/computational_performance.html

**Comment by Athanaseus** [comment]
> Do I understand correctly that parallel_gridding is only used when use_wgridder: False?

Yes, that's correct.

**Comment by paoloserra** [comment]
What do we mean with "This can make things faster in certain cases"? Is there any case where parallel w-stacking is not faster than non-parallel w-stacking, provided you have enough RAM?

**Comment by Athanaseus** [comment]
That was a line from WSClean documentation.

```
-parallel-gridding <n>
   Will execute multiple gridders simultaneously. This can make things faster in certain cases,
   but will increase memory usage. 
```
How does this sound now:

```
          nr_parallel_grid:
            type: int
            example: '1'
            required: false
            desc: Will execute multiple gridders simultaneously when using w-stacking. When parallel gridding is not possible, or when image sizes are reasonably large (say 5k-10k), the w-gridder might be a better choice.
```

**Review by paoloserra — DISMISSED** [review]

**Review by paoloserra — APPROVED** [review]

**Pull request merged**
