### PR TITLE
predict noise of line cube

### PR DESCRIPTION
**Pull request by paoloserra**
This PR allows users to estimate the natural noise of the line cubes given Tsys/eff and the dish diameter. The implementation is a shameless copy-paste from https://github.com/paoloserra/noisy . The noise estimate is printed to log-caracal.txt .

With _some_ delay, this addresses #65 (closed long ago for lack of faith).

This PR also fixes some minor errors in the line worker.

### CODE REVIEW

**Comment by paoloserra** [comment]
Could somebody with superpowers copy-paste the test error? (I have no access to the relevant pages, or forgot how to get there.)

**Comment by gigjozsa** [comment]
Very enigmatic. Click here for the full log:
[consoleFull.txt](https://github.com/caracal-pipeline/caracal/files/5493930/consoleFull.txt)

The error is as follows:
```
2020-11-04 21:05:06 CARACal.Stimela.save-mypipelinerun_line_after-mst0 INFO: job complete at 2020-11-04 21:05:06.341654 after 0:00:06.100290
2020-11-04 21:05:06 CARACal INFO: Predicting natural noise of line cubes (Stokes I, single channel) for Tsys/eff = 20.5 K, diam = 13.5 m -> SEFD = 395.5 Jy
2020-11-04 21:05:06 CARACal INFO:   Target #0: circinus-p3, files ['1532022061_subset-circinus_p3-corr_mst.ms']
2020-11-04 21:05:06 CARACal INFO:  CATASTROPHE!
2020-11-04 21:05:06 CARACal INFO:  Cannot find the field you want to process, circinus_p3
2020-11-04 21:05:06 CARACal INFO:  Available fields are ['circinus-p3']
2020-11-04 21:05:06 CARACal INFO:  Aborting ...
2020-11-04 21:05:06 CARACal ERROR: A pipeline worker initiated sys.exit(None). This is likely a bug, please report.
2020-11-04 21:05:06 CARACal INFO:   More information can be found in the logfile at output/logs-20201104-203557/log-caracal.txt

```

**Comment by gigjozsa** [comment]
@paoloserra What happens if you click on "Details"?

**Comment by paoloserra** [comment]
Thanks @gigjozsa
The difference is between `-` and `_`

**Comment by dane-kleiner** [comment]
> @paoloserra What happens if you click on "Details"?

I tried and it wants me to log into a Jenkins something, which I don't believe I have access to..

**Comment by gigjozsa** [comment]
How does this occur? Are you replacing all _s with -s in the whole string (excuse my laziness)?

**Comment by paoloserra** [comment]
> How does this occur? Are you replacing all _s with -s in the whole string (excuse my laziness)?

No I'm not, that's why I'm a little puzzled, but  I'm looking into it

**Comment by paoloserra** [comment]
@gigjozsa I don't think it's me though.

My code is looking for `circinus_p3` because that  is the output of

https://github.com/caracal-pipeline/caracal/blob/fa5095367235c2854b657cd6955188efe2af2036/caracal/workers/line_worker.py#L698

where `target = circinus-p3`.

And `circinus_p3` cannot  be found in

https://github.com/caracal-pipeline/caracal/blob/fa5095367235c2854b657cd6955188efe2af2036/caracal/dispatch_crew/noisy.py#L46

because  the latter is = `['circinus-p3']`

The change happens in https://github.com/caracal-pipeline/caracal/blob/fa5095367235c2854b657cd6955188efe2af2036/caracal/dispatch_crew/utils.py#L367-L369

which is used throughout the code. Indeed, look at your target-only MS file names. They've got `circinus_p3` in them, not `circinus-p3`.

**Comment by paoloserra** [comment]
It's an easy change though, I just need to set `field = target` in 

https://github.com/caracal-pipeline/caracal/blob/fa5095367235c2854b657cd6955188efe2af2036/caracal/workers/line_worker.py#L698

**Comment by paoloserra** [comment]
ok to test

**Comment by paoloserra** [comment]
> What happens if you click on "Details"?

I'm also taken to a google login page, but I don't really know what account I  should use there. Sorry, I probably  used to know, but it's been a while.

**Review by gigjozsa — CHANGES_REQUESTED** [review]
Sorry, could someone countercheck:
If I take the length of the observation from 1532022061_subset-circinus_p3-corr_mst-obsinfo.txt 17689s, 32 ants, Tsys/eta = 20.5, D=13.5m, the radiometre formula gives me 0.146 mJy, not 0.121, which is the output of the calculator.

**Comment by paoloserra** [comment]
> Sorry, could someone countercheck:
> If I take the length of the observation from 1532022061_subset-circinus_p3-corr_mst-obsinfo.txt 17689s, 32 ants, Tsys/eta = 20.5, D=13.5m, the radiometre formula gives me 0.146 mJy, not 0.121, which is the output of the calculator.

I agree that in your case it should be 0.146 mJy/beam for channel width = 209 kHz (4k mode, right?).

However, I've double checked this numerous times and it's always been OK. This is a recent example with 61 antennas:

```
2020-11-04 23:53:09 CARACal INFO:   CHAN_FREQ from 1350820327.591151 Hz to 1429182937.4544322 Hz with average channel width of 6530.76171875 Hz
...
2020-11-04 23:53:09 CARACal INFO:     mfs32 (ID=2) : 266.89 minutes | RA=54.88 deg, Dec=-35.72 deg
...
2020-11-04 23:55:46 CARACal INFO:     ignoring flags: median = 4.514e-04 Jy/beam, range = (4.514e-04 - 4.514e-04) Jy/beam
```

The radiometer equation gives 4.518e-04 Jy/beam, which agrees with this PR.

Can you maybe share those same lines from your `log-caracal.txt` here? Are you sure about the integration time?

**Comment by gigjozsa** [comment]
This is from the Jenkins test:
[1532022061_subset-circinus_p3-corr_mst-obsinfo.txt](https://github.com/caracal-pipeline/caracal/files/5502819/1532022061_subset-circinus_p3-corr_mst-obsinfo.txt)
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/5502820/log-caracal.txt)
I'm sure I made a mistake...

**Comment by paoloserra** [comment]
I think I know what's happening.

Your log-caracal.txt says

```
2020-11-05 11:41:10 CARACal INFO:     circinus-p3 (ID=2) : 203.25 minutes | RA=213.31 deg, Dec=-65.34 deg
```

So that's 12,195 seconds and not 17,689 -- not sure where you got the latter from :)

So the noise should be 0.1758 mJy/beam while this PR predicts 0.121 mJy/beam ~ 0.1758 / sqrt(2).

I think this is because your MS has XX,YY,XY,YX and the script does not realise it should only consider two of those for the noise estimate.

**Comment by gigjozsa** [comment]
Ah. The 18k seconds came from the obsinfo. I reasoned that just taking the length of the observation would provide a lower limit to the rms. I was not looking for the sqrt(2). Could you implement a correction if there are 4 correlation products in the data?

**Comment by paoloserra** [comment]
Yes I will

**Comment by paoloserra** [comment]
@gigjozsa it should be fixed now. Can you please try again?

Note that I've increased the level of verbosity at https://github.com/caracal-pipeline/caracal/blob/832fb46cf9e5d5e7c9236354aa62840f5f79bc52/caracal/workers/line_worker.py#L699

It can be changed back to `verbose=1`, but maybe it's OK as is.

**Comment by paoloserra** [comment]
OK to test

**Comment by paoloserra** [comment]
ok to test

**Comment by gigjozsa** [comment]
Will look now right after passing the test.

**Comment by paoloserra** [comment]
> Will look now right after passing the test.

done

**Review by gigjozsa — APPROVED** [review]

**Comment by gigjozsa** [comment]
First thing in the morning, just as promised...

**Pull request merged**
