### PR TITLE
Correct issue #1285

### PR DESCRIPTION
**Pull request by Mulan-94**
An attempt at issue #1285

### CODE REVIEW

**Comment by Mulan-94** [comment]
@paoloserra I hope this fixes it and thanks for pointing it out :) !

**Comment by paoloserra** [comment]
ok to test

**Review by paoloserra — APPROVED** [review]
works for me

**Comment by o-smirnov** [comment]
Can I request another small fix while we're at it? The schema allows for a setting of "none" to disable the standard plots, but this currently bombs out with ``KeyError: 'none'``. Adding

```
             if plotter and plotter != "none":
```

should be sufficient.

I'm very annoyed that pykwalify won't support a proper ``None`` value, but not annoyed enough to rewrite it (yet).

**Comment by Mulan-94** [comment]
oops @o-smirnov shall I make a new branch?

**Comment by o-smirnov** [comment]
I dunno if that's necessary, a cheeky commit to this one / new PR will also do...

**Comment by Mulan-94** [comment]
Ok, new PR it is

**Pull request merged**
