### PR TITLE
Mauchian mosaic

### PR DESCRIPTION
**Pull request by svw26**
In 'continuum' mode, giving the user the option to choose between 'Gaussian' and 'Mauchian' for generating primary beams (where they are not already present). Also updated a flag-schema description whilst I'm at it.

### CODE REVIEW

**Comment by o-smirnov** [comment]
Retest this please.

**Comment by gigjozsa** [comment]
I have sneaked in the solution of #1230

**Comment by gigjozsa** [comment]
Solves #1230

**Comment by gigjozsa** [comment]
Resolves #1230

**Comment by gigjozsa** [comment]
Something is not ok with Jenkins. I cannot reach the server either.

**Comment by gigjozsa** [comment]
retest this please

**Review by gigjozsa — APPROVED** [review]

**Comment by gigjozsa** [comment]
@svw26 you want to do the honors and merge?

**Pull request merged**
