### PR TITLE
External mask

### LINKED ISSUE #1370: Option for using external mask to image the secondary calibrator
Is there a way to use an external mask for imaging the secondary calibrator in caracal or would imaging it with wsclean outside caracal be the way to go? I'm not happy with the model I'm getting through auto masking (in 1GC) as it includes artefacts around the calibrator. I attach the config file and log file for reference
[test254.txt](https://github.com/caracal-pipeline/caracal/files/7191655/test254.txt)
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/7191656/log-caracal.txt)

### PR DESCRIPTION
**Pull request by Athanaseus**
- Use an external mask to image the secondary calibrator.
resolves #1370

### CODE REVIEW

**Comment by paoloserra** [comment]
@Athanaseus the docs say:

>  external_fits_masks: desc: List of prefix strings to use an existing .FITS mask located in input/. NB: the masks need to be on the same WCS grid as the images being made and the naming must have the field ID in the prefix. e.g. prefix-<fid>. Otherwise a WSClean's auto-masking will be used (threshold set by auto_mask below)

I don't completely understand the naming of the mask FITS files.

According to the docs we request a list of prefix strings, not the full FITS names. But looking at the code it seems to me that we're actually requesting full FITS names. There's a difference, because if you tell me I need to give you a prefix then I start wondering what should go after the prefix.

Also, I'm not sure that the matching between FITS name and `fid` is unique. In the code I see the line:

> if fid in mask:

What happens if you have field 1 and field 10 in the MS? The mask `mystrangemaskname-10.fits` would be OK both for `fid = 1` and `fid = 10`? And in that case, does the code take the last match (since you're in a `for` loop)?

Please clarify this and make any necessary changes before we merge.

**Comment by Athanaseus** [comment]
@paoloserra can you please have a look and issue `ok to test`.

> I don't completely understand the naming of the mask FITS files.

User provides prefix and the extension is append in the code.

> Also, I'm not sure that the matching between FITS name and fid is unique. In the code I see the line.

Ok now we strip out the fid from the fits image and match it to the `str(fid)`.

> What happens if you have field 1 and field 10 in the MS? The mask mystrangemaskname-10.fits would be OK both for fid = 1 and fid = 10? And in that case, does the code take the last match (since you're in a for loop)?

Good catch, this should be resolved in the above comment.

**Comment by paoloserra** [comment]
> > I don't completely understand the naming of the mask FITS files.
> 
> User provides prefix and the extension is now appended in the code.

So what you're calling prefix in the documentation is actually the full FITS file name without extension?

**Comment by Athanaseus** [comment]
> So what you're calling prefix in the documentation is actually the full FITS file name without extension?

Yes, that's correct.

**Comment by paoloserra** [comment]
Sorry but that's not what the docs say.

> desc: List of prefix strings to use an existing .FITS mask located in input/. NB [...] the naming must have the field ID in the prefix. e.g. prefix-\<fid>. [...]

The example you give in the docs is confusing because the field id is not part of the prefix, but is added to it. So it suggests that what you call `prefix` is not the full file name.

I think it's a lot easier if we don't talk about prefixes but just about file names, and clarify whether there is any rule to place the field id within the file name.

Can you please edit the docs to be clearer? If I were a user I wouldn't be sure what to do.

**Comment by Athanaseus** [comment]
> Can you please edit the docs to be clearer? If I were a user I wouldn't be sure what to do.

List of file names (without .FITS extension) located in input/. The naming must have the field ID in the file name. e.g. specify as "mask-image-4" for a file called "mask-image-4.fits" in input/ where "4" is the field ID. NB - the masks need to be on the same WCS grid as the images being made. Otherwise a WSCleans auto-masking will be used (threshold set by auto_mask below)

**Review by paoloserra — APPROVED** [review]

**Comment by paoloserra** [comment]
test this please

**Comment by paoloserra** [comment]
test this please

**Pull request merged**
