### PR TITLE
Mask forn

### PR DESCRIPTION
**Pull request by Fil8**
Major updates are that now the user can provide an input mask (in `output/masking`) for cleaning, or to add on top of SoFiA's result and then be used in cycle 1,2.. of cleaning.

- I commented the functions 'fornax_special' which are now outdated. They can be deleted in my opinion.
- an old typo-inconsistency in the line worker has been fixed

### CODE REVIEW

**Comment by paoloserra** [comment]
Thanks @Fil8 , I'll have a look soon

**Comment by francescaLoi** [comment]
I found two issues with this branch:
1) this line must be idented:
https://github.com/caracal-pipeline/caracal/blob/f53f8df7ff452acfa3ae908e8b0a5ceb73842963/caracal/workers/selfcal_worker.py#L925 

2) The default value of the multiscale_bias in the `selfcal_schema.yml` is an empty string while according to the descripion should be the float number 0.6.

**Comment by Fil8** [comment]
I did solve the issues mentioned by @francescaLoi

**Comment by Athanaseus** [comment]
Hi @Fil8, thank you for resolving the issues.
Last thing that could be missing according to the test failure:
```
Run # stop the build if there are Python syntax errors or undefined names
./caracal/workers/selfcal_worker.py:667:18: F821 undefined name 'fits'
            with fits.open('{}/{}'.format(pipeline.masking,preGridMask)) as hdul:
                 ^
./caracal/workers/selfcal_worker.py:711:22: F821 undefined name 'fits'
                with fits.open('{}/{}'.format(pipeline.masking,preGridMask)) as hdul:
                     ^
./caracal/workers/selfcal_worker.py:745:22: F821 undefined name 'fits'
                with fits.open('{}/{}'.format(pipeline.masking,postGridMask), mode='update') as hdul:
                     ^
./caracal/workers/selfcal_worker.py:841:18: F821 undefined name 'fits'
            with fits.open('{}/{}'.format(pipeline.masking,preGridMask)) as hdul:
                 ^
./caracal/workers/selfcal_worker.py:857:26: F821 undefined name 'fits'
                hduImage=fits.getheader('{}/{}'.format(pipeline.output,imagename))
                         ^
./caracal/workers/selfcal_worker.py:882:22: F821 undefined name 'fits'
                with fits.open('{}/{}'.format(pipeline.masking,preGridMask)) as hdul:
                     ^
./caracal/workers/selfcal_worker.py:911:26: F821 undefined name 'fits'
                datTmp = fits.getdata('{}/{}'.format(pipeline.masking,postGridMask))
                         ^
./caracal/workers/selfcal_worker.py:912:27: F821 undefined name 'fits'
                headTmp = fits.getheader('{}/{}'.format(pipeline.masking,postGridMask))
                          ^
./caracal/workers/selfcal_worker.py:922:[17](https://github.com/caracal-pipeline/caracal/actions/runs/11054987115/job/30713110584#step:9:18): F821 undefined name 'fits'
                fits.writeto('{}/{}'.format(pipeline.masking,postGridMaskSof),datNew,headTmp,overwrite=True) 
                ^
./caracal/workers/selfcal_worker.py:951:23: F8[21](https://github.com/caracal-pipeline/caracal/actions/runs/11054987115/job/30713110584#step:9:22) undefined name 'fits'
.
.
.
```
is
```
@extras("astropy")
def image(trg, num, img_dir, mslist, field):
    import astropy.io.fits as fits
```

and in all functions using the `astropy` io.fits such as `sofia_mask(trg, num, img_dir, field), etc`

**Review by paoloserra — DISMISSED** [review]
Looks good to me, thanks!

Just some minor comments on the selfcal schema:
- baises -> biases
- cleaning.  balances -> cleaning. This balances
- Its default is 0.6 -- but actually the default is an empty string
- will be (regridded if needed) and added -> will be (regridded if needed and) added

**Review by paoloserra — APPROVED** [review]

**Comment by SpheMakh** [comment]
ready to test

**Comment by SpheMakh** [comment]
ok to test

**Comment by paoloserra** [comment]
> Looks good to me, thanks!
> 
> Just some minor comments on the selfcal schema:
> 
>     * baises -> biases
> 
>     * cleaning.  balances -> cleaning. This balances
> 
>     * ~Its default is 0.6 -- but actually the default is an empty string~ (fixed below)
> 
>     * will be (regridded if needed) and added -> will be (regridded if needed and) added

All fixed now

**Review by paoloserra — DISMISSED** [review]

**Comment by paoloserra** [comment]
ok to test

**Review by paoloserra — APPROVED** [review]

**Pull request merged**
