### PR TITLE
What the flag

### LINKED ISSUE #1299: CARACal crashes on permission error when copying logos
I'm finding that the line which the copies CARACal logos from the local repository to `output/reports/` https://github.com/caracal-pipeline/caracal/blob/3caefccb72eaee9f560c53b8af7733c3038ece68/caracal/notebooks/__init__.py#L23 causes CARACal to crash on a permission error when the `output` folder (as well as `output/reports/` and all its content) was created by a different user, even though I have write access there.

The error is

```
2020-12-15 17:00:23 CARACal INFO: Copying MeerKAT input files into input folder
2020-12-15 17:00:23 CARACal ERROR: [Errno 1] Operation not permitted [PermissionError]
2020-12-15 17:00:23 CARACal INFO:   More information can be found in the logfile at output/logs-20201215-165958/log-caracal.txt
2020-12-15 17:00:23 CARACal INFO:   You are running version 1.0.4
2020-12-15 17:00:23 CARACal ERROR: Traceback (most recent call last):
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/main.py", line 175, in __run
2020-12-15 17:00:23 CARACal ERROR:     end_worker=options.end_worker, generate_reports=not options.no_reports)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 138, in __init__
2020-12-15 17:00:23 CARACal ERROR:     self.init_pipeline(prep_input=config["general"]["prep_workspace"])
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 342, in init_pipeline
2020-12-15 17:00:23 CARACal ERROR:     notebooks.setup_default_notebooks(all_nbs, output_dir=self.output, prefix=self.prefix, config=self.config)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/notebooks/__init__.py", line 23, in setup_default_notebooks
2020-12-15 17:00:23 CARACal ERROR:     shutil.copy2(png, logodir)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/shutil.py", line 264, in copy2
2020-12-15 17:00:23 CARACal ERROR:     copystat(src, dst, follow_symlinks=follow_symlinks)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/shutil.py", line 205, in copystat
2020-12-15 17:00:23 CARACal ERROR:     follow_symlinks=follow)
2020-12-15 17:00:23 CARACal ERROR: PermissionError: [Errno 1] Operation not permitted
2020-12-15 17:00:23 CARACal INFO: exiting with error code 1
```

The problem disappears if I replace that line with

```
shutil.copyfile(png, os.path.join(logodir,os.path.basename(png)))
```

I actually don't understand this -- neither the error (I do have write access there) nor the fix. So I'm not sure this is the solution we want, but it does seem to work.

Any clue?

Tagging @o-smirnov and @Jordatious since I mentioned this to them elsewhere.

### PR DESCRIPTION
**Pull request by paoloserra**
This PR lumps together a bunch of changes we're using to process the Fornax data:

- **Flag versions.** In the `selfcal` worker, if no new flags are going to be created for the `label_in` MS (e.g., because we are not running cubical/meqtrees on it), then do not save the `before_worker` and `after_worker` flag versions for that MS. The old behaviour of saving those (unnecessary) flag versions was in principle harmless. However, it was causing problems when simultaneously tranferring & applying gains from a single `label_in` MS to different `transfer_to_label` MS files on different CPUs. Each CPU was trying to write the same, unnecessary flag versions for the `label_in` MS, making a mess. @o-smirnov please check this out.

- **Known HI.** Update of the Fornax catalogue of known HI detections, which can be used when automatically excluding bright HI channels from the UVLIN fit in `line:mstransform:uvlin`.

- **Bandpass smoothing.** Implemented smoothing of the bandpass solution using a mean running window. The size of the window is set by `crosscal:primary:b_smoothwindow` and `crosscal:secondary:b_smoothwindow`. The default is 0 and means no smoothing.  The smoothing operates separately on the real and imaginary part of the complex, antenna-based bandpass. See https://github.com/caracal-pipeline/caracal/issues/1283. Alternative smoothing methods are left for future PRs.

- **Mosaic (1).** More flexibility on the location of the images and cubes to be mosaicked. These needed to be located in (sub-directories of) `general:output/continuum` and `general:output/cubes`, respectively. This does not work well when the different pointings are reduced in different directories and, therefore, do not share the same `general:output` directory. With this PR the input images and cubes need to be located more generally in (subdirectories of) the CWD, which is less restrictive. See https://github.com/caracal-pipeline/caracal/issues/1290.

- **Mosaic (2).** Before mosaicking spectral-line cubes, check that all input cubes have the same `CDELT3` value. If not, throw an error and exit the pipeline gracefully to prevent `montage` from crashing. In case of inconsistent `CDELT3`, it is possible that the differences are not significant and simply due to precision issues (for example, differences at the level of ~ 1 microHz for channel widths of ~ 1 kHz can arise even when _explicitly Doppler correcting the MS files of all pointings to the same barycentric frequency grid_). In such cases, one can ignore those differences by rounding the `CDELT3` values before mosaicking. This overwrites the `CDELT3` header key of the input cubes. The number of decimals is set by `mosaic:round_cdelt3`. The default value is 0 and means no rounding.

- **Mosaic (3).** Convert header keys `crval3,crval4,crpix3,crpix4,cdelt3,cdelt4,crota2` to floats in all mosaic FITS files. See https://github.com/caracal-pipeline/caracal/issues/1273 . Add median `bmaj,bmin,bpa` and `bunit` to all mosaic FITS files. Some of these changes can be undone if/when incorporated in https://github.com/svw26/MosaicSteward by @svw26.

- **Sunblocker.** Fix naming error of output SVG plots.

- Fix #1299 

This is mostly spectral line stuff so I'm tentatively requesting a review from @gigjozsa , but everybody else should feel free to jump on it. Thanks.

### CODE REVIEW

**Comment by paoloserra** [comment]
Can somebody with access to RARG Jenkins please copy the error here? Thanks.

**Comment by gigjozsa** [comment]
@paoloserra
@o-smirnov 
@bennahugo

This is the "Dockerhub playing silly buggers" (this is a citation) error.
```
Running stimela pull -d
# running docker pull stimela/shadems:1.7.0
# Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_meerkathi/workspace/269/test-output/8a66b21/caracal_venv/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/var/lib/jenkins/jobs/PR_meerkathi/workspace/269/test-output/8a66b21/caracal_venv/lib/python3.6/site-packages/stimela/main.py", line 567, in main
    _cmd(argv)
  File "/var/lib/jenkins/jobs/PR_meerkathi/workspace/269/test-output/8a66b21/caracal_venv/lib/python3.6/site-packages/stimela/main.py", line 295, in pull
    docker.pull(image, force=args.force)
  File "/var/lib/jenkins/jobs/PR_meerkathi/workspace/269/test-output/8a66b21/caracal_venv/lib/python3.6/site-packages/stimela/docker.py", line 57, in pull
    utils.xrun("docker", ["pull", image])
  File "/var/lib/jenkins/jobs/PR_meerkathi/workspace/269/test-output/8a66b21/caracal_venv/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: docker returns error code 1
stimela pull -d failed

```

**Comment by o-smirnov** [comment]
No, this is the docker daemon succumbing to covid-19 error:
```
# Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Seems to be happening all over?

**Comment by gigjozsa** [comment]
Checking now.

**Comment by paoloserra** [comment]
Any news on this?

**Comment by gigjozsa** [comment]
It does not happen everywhere. I just successfully installed and ran CARACal with Docker on two workstations stevie and ray.

**Comment by gigjozsa** [comment]
@bennahugo @o-smirnov what to do?

**Comment by bennahugo** [comment]
Sorry forgot to mention that we traced the root cause of this thanks to Sakhile. 
container.d was auto updated as part of daily security updates. The daemon can simply be restarted (sudo service docker restart)

**Comment by bennahugo** [comment]
retest this please

**Comment by paoloserra** [comment]
thanks @bennahugo

**Comment by HaoChen-ast** [comment]
Hi @paoloserra, Besides `CDELT3`, the inconsistent of `crval3` will also prevent `montage` from working correctly. 

With the inconsistent `CDELT3` or `crval3`, `montage` will create '*.hdr' header file without `CRPIX3` and `CDELT3` and report error later as the HI cubes have the frequency (or velocity) axis.

**Comment by paoloserra** [comment]
Thanks for the comment @HaoChen-ast . Have you found yourself in a situation with varying crval3?

**Comment by HaoChen-ast** [comment]
@paoloserra 
Yes, the following 4 nights data I reduced for GPS have different `crval3` and `cdelt3`. 
I also worried about `cdelt3` could be 208976 Hz for some data, then rounding will not work.

1547413577:   crval3  1307976527.477 Hz        cdelt3 208975.320000172 Hz
1547330621:   crval3  1307975190.106 HZ       cdelt3 208975.105999947 Hz
1547071945:   crval3  1307975190.106 Hz        cdelt3 208975.105999947 Hz
1547499081:   crval3  1307978987.004 Hz       cdelt3 208975.712999821 Hz

**Comment by paoloserra** [comment]
These differences seem a little extreme and not really in the ballpark of what this PR is about. Here I was considering a case in which all MS files were Doppler corrected to a _**common**_ barycentric frequency grid, and small rounding errors got in the way of mosaicking. Is it possible that in your case each MS was Doppler corrected to a different barycentric frequency grid? If so, I don't think you should solve it by rounding things up. You would want to take a step back, regrid all MS files to a common barycentric frequency grid, and try again.

**Comment by HaoChen-ast** [comment]
Yes, you are right.
My MS was Doppler corrected to a different barycentric grid.
Before Doppler correction, the TOPO frequency grids are exactly the same.
I should regrid all MS files to a common barycentric frequency grid after Doppler correction.
And check `crval3` and `cdelt3` again.

**Comment by paoloserra** [comment]
yeah -- my experience is that the crval3 values will all be identical then. If that's not the case please let me know.

**Comment by paoloserra** [comment]
retest this please

**Comment by paoloserra** [comment]
retest this please

**Comment by dane-kleiner** [comment]
> retest this please

Early next week, I promise!

**Review by dane-kleiner — APPROVED** [review]
Looks good to me!

**Pull request merged**
