### PR TITLE
Add wsclean models for primary calibrators in MeerKAT UHF band

### PR DESCRIPTION
**Pull request by KshitijT**
This PR adds custom wsclean models (made by @bennahugo ) for MeerKAT UHF band calibrators ( 1934 and 0407 only for the moment) where field structure  is (more?) important than at L-band. Tries to address #1357 . 

Summary:
1. Adds new keywords to crosscal schema including one to be used for the band (L/UHF) - this is not used currently but would be needed once L-band wsclean models are added.
2. Adds keywords for crystalball prediction to crosscal schema.
3. Adds two wsclean models for 1934 and 0407.
4. Alters the catalog_parser and utils in dispatch_crew to accommodate the wsclean model (see the new mode "crystal")
5. Changes the crosscal worker to allow crystalball prediction of the wsclean models.
6. Adds an optional UHF flagging strategy, should be of help with #1349 .

### CODE REVIEW

**Review by SpheMakh — APPROVED** [review]
Looks good

**Comment by KshitijT** [comment]
> Looks good

But of course !

**Comment by KshitijT** [comment]
Sorry @SpheMakh , restoring the UHF branch, still have plans for it.

**Comment by SpheMakh** [comment]
Create a new branch. This one has been merged, it has to be deleted.

**Comment by o-smirnov** [comment]
Doesn't have to be deleted though. You can merge from a branch multiple times. Often happens with long-running dev branches.

(Not that I'm a fan of long-running dev branches! Short feature branches FTW please.)

**Comment by SpheMakh** [comment]
Agreed, but let's avoid long-running branches. I suggest starting a project with multiple branches if you envision long-running dev work for a specific issue.

**Pull request merged**
