### PR TITLE
Update region module for ddcal

### LINKED ISSUE #1429: Adjust ddcal worker to accommodate new regions layout
https://github.com/caracal-pipeline/caracal/blob/55737c6311f12c09a73db27c1557abe3f413c9a3/caracal/workers/ddcal_worker.py#L11

write_ds9 does not exist any more  in regions. Either one needs to specify the regions version in the system file or reprogram ddcal worker

### LINKED ISSUE #1438: update of regions package breaking ddcal worker
Fresh install of stable caracal release has an ImportError with the ddcal worker due to an update to the regions package to version 0.6:

`Traceback (most recent call last):`
  `
File "/home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers/worker_administrator.py", line 115, in __init__
    wkr = __import__(_worker)
`
  `
File "/home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers/ddcal_worker.py", line 11, in <module>
    from regions import PixCoord, write_ds9, PolygonPixelRegion
`
`ImportError: cannot import name 'write_ds9' from 'regions' (/home/knowles/caracal-venv/lib/python3.8/site-packages/regions/__init__.py)`
`2022-08-01 13:03:50 CARACal ERROR: Worker "ddcal_worker" could not be found at /home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers [ImportError]`

Force-install of an earlier regions package fixes the problem:
`pip install "regions<0.6"`

### PR DESCRIPTION
**Pull request by Athanaseus**
resolves #1438
resolves #1429

### CODE REVIEW

**Review by paoloserra — APPROVED** [review]

**Comment by paoloserra** [comment]
retest this please

**Comment by bennahugo** [comment]
Just a note there is definitely breakage in newer Regions parsing. Regions files that read fine with DS9 fail to open due to some coordinate system specification issues in the comment lines. I tried this fix for cubical itself, but I've decided to downgrade and revert to previous versions, see https://github.com/ratt-ru/CubiCal/pull/465

**Comment by KshitijT** [comment]
> Just a note there is definitely breakage in newer Regions parsing. Regions files that read fine with DS9 fail to open due to some coordinate system specification issues in the comment lines. I tried this fix for cubical itself, but I've decided to downgrade and revert to previous versions, see [ratt-ru/CubiCal#465](https://github.com/ratt-ru/CubiCal/pull/465)

Bleh, maybe it's time to redesign this worker from scratch..

**Comment by bennahugo** [comment]
I've just spotted there is an issue in crystalball as well due to this. Will submit a downgrade PR now

**Comment by bennahugo** [comment]
> > Just a note there is definitely breakage in newer Regions parsing. Regions files that read fine with DS9 fail to open due to some coordinate system specification issues in the comment lines. I tried this fix for cubical itself, but I've decided to downgrade and revert to previous versions, see [ratt-ru/CubiCal#465](https://github.com/ratt-ru/CubiCal/pull/465)
> 
> Bleh, maybe it's time to redesign this worker from scratch..

I still think regions files are the way to go -- they are certainly much easier to work with than casa latices. We just need to be careful with the regions parsers we use

**Comment by Athanaseus** [comment]
Thanks @bennahugo, then it makes sense to roll this back and just pin it to the previous version of regions.

Also, I notice that the latest regions require python>=3.8. .ie. users running lower versions of python will get previous versions of regions.

**Comment by KshitijT** [comment]
Do not merge (see comments by @bennahugo and @Athanaseus above).

**Review by KshitijT — DISMISSED** [review]
Looks ok to me.

**Comment by KshitijT** [comment]
@Athanaseus , please update the branch and then it should be good to go.

**Comment by KshitijT** [comment]
> Athanaseus dismissed KshitijT’s stale review via b150526 1 hour ago. 

😢

**Review by KshitijT — APPROVED** [review]
Looks good to me.

**Comment by KshitijT** [comment]
@Athanaseus please merge when ready.

**Pull request merged**
