### PR TITLE
Reinstate singularity Jenkins test

### PR DESCRIPTION
**Pull request by gigjozsa**
Reinstate Singularity Jenkins test without the need for > v3.5 Singularity. Notice that this will not alter the Singularity cache dir, which may be anywhere.

### CODE REVIEW

**Comment by gigjozsa** [comment]
Resolves #1155

**Comment by gigjozsa** [comment]
This PR creates the stimela_pullfolder in the workspace. If this works, then this mimics a situation where one re-uses images already built in a former run.

**Comment by gigjozsa** [comment]
retest this please

**Comment by gigjozsa** [comment]
retest this please

**Comment by gigjozsa** [comment]
@SpheMakh @o-smirnov with any luck the Jenkins test is now the double test which tests less the strength of the network rather than the code:
It will do a docker run with a complete installation etc.
Then it will do a singularity run but setting the pullfolder to a permanent directory.
It will not change the location of the singularity cache, though, because as @SpheMakh has found out this leads to problems when defining a pullfolder at the same time.

I let it run (with success) once and I am now re-running it with exactly the same parameters, which should result in a much faster success as the pullfolder is already populated.

It will, however, rerun the radiopadre pull. Will follow up with @o-smirnov on that.

**Comment by bennahugo** [comment]
Note that I originally disabled this because singularity hangs indefinitely
on network errors. So re-enabling it without a timer to send an interrupt
is not recommended.

**Pull request merged**
