### PR TITLE
Add nwlayer_factor option to wsclean

### PR DESCRIPTION
**Pull request by KshitijT**
Sorts out #1187 . Note that this needs stimela branch nwlayer_factor to work. DO NOT MERGE until the branch goes through to the release version.

EDIT: Works with master version now.

### CODE REVIEW

**Comment by KshitijT** [comment]
With the new stimela release this should be good to go.

**Comment by KshitijT** [comment]
Retest this please.

**Comment by KshitijT** [comment]
@paoloserra , @SpheMakh could you please take a look at this PR and give your review?
@SpheMakh , thanks for the Stimela release.

**Comment by KshitijT** [comment]
@paoloserra , the conflicts with the master branch are now resolved.

**Comment by paoloserra** [comment]
@KshitijT I'm just not sure about the description of this  new parameter. What is "approximately true"? And in "if the number of cores available are larger", do you mean larger than the requested nr of w-layers or than the value or nwlayer_factor? In general, it would be good if the description could be understood by a user without having to go to the wsclean page. Thanks!

**Comment by KshitijT** [comment]
> @KshitijT I'm just not sure about the description of this new parameter. What is "approximately true"? And in "if the number of cores available are larger", do you mean larger than the requested nr of w-layers or than the value or nwlayer_factor? In general, it would be good if the description could be understood by a user without having to go to the wsclean page. Thanks!

Right, I have altered the description to be easier to understand ( I hope).

**Comment by paoloserra** [comment]
Perfect, thanks. I've noticed that the new description takes two lines in the schema fine. If that's allowed then all good, otherwise please bring it back to a single line.

**Comment by KshitijT** [comment]
> Perfect, thanks. I've noticed that the new description takes two lines in the schema fine. If that's allowed then all good, otherwise please bring it back to a single line.

Well spotted, thanks ! Fixed that too now.

**Review by paoloserra — APPROVED** [review]

**Comment by paoloserra** [comment]
Retest this please.

**Pull request merged**
