### PR TITLE
PB cube Stokes axis

### PR DESCRIPTION
**Pull request by paoloserra**
If the image cube has a Stokes axis, the primary beam cube should have it too.

### CODE REVIEW

**Review by gigjozsa — COMMENTED** [review]
Please notice that I merged these changes into branch imcontsub. Please check and approve pull request there if appropriate, and delete this branch without merging.

**Comment by gigjozsa** [comment]
@paoloserra Please notice that mosaic worker works for cubes only if remove_stokes_axis is activated. Is this correct?

**Comment by paoloserra** [comment]
retest this please

**Comment by paoloserra** [comment]
close this as the changes are already in #1443

**Pull request closed without merging**
