### PR TITLE
Allow for mstransform to split antennas

### PR DESCRIPTION
**Pull request by PeterKamphuis**
Allow to use mstransform to split antennas within caracal. 

I noticed in testing that when removing antennas this shifts the antenna ID in listobs. NAME and STATION are preserved and those are listed in the json summary so I think this should not cause any problem but I wanted to catalogue it.

### CODE REVIEW

**Comment by PeterKamphuis** [comment]
Ok I can not see what goes wrong here

**Comment by Athanaseus** [comment]
> Ok I can not see what goes wrong here

The tests use the latest release of `stimela`. This means that the antenna param for `mstransform` has not yet propagated through, as I think you tested this against `stimela` master.
As soon as a release is made I'll hit the retest button and approve.

**Comment by PeterKamphuis** [comment]
@Athanaseus I suspected that but I can not see it. In the sense that I do not have access to Jenkins. In anycase let's wait for the new stimela release then.

**Review by Athanaseus — APPROVED** [review]
LGTM!

**Comment by Athanaseus** [comment]
retest this please

**Pull request merged**
