### PR TITLE
fixing labels and cleaning the postcal imaging function

### LINKED ISSUE #1322: wrong mask name in ddcal worker
I noticed that the output mask name in the postcal step "make a mask for the initial ddf image" is wrong:
https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/workers/ddcal_worker.py#L166

It should be:
`                 'output' : '{0:s}mask_ddf_postcal_{1:s}.fits:output'.format(output_folder,field),`

I'll soon push a change to fix it.

### PR DESCRIPTION
**Pull request by francescaLoi**
This will close #1322

### CODE REVIEW

**Review by KshitijT — APPROVED** [review]
LGTM.

**Comment by francescaLoi** [comment]
> LGTM.

I've found two meanings for this: 1. "Literally Garbage To Me" and 2. "Looks Good To Me".
Hope this is a number 2 case :)

**Comment by KshitijT** [comment]
> > LGTM.
> 
> I've found two meanings for this: 1. "Literally Garbage To Me" and 2. "Looks Good To Me".
> Hope this is a number 2 case :)

Well, I hope the approval of the PR helps you select the correct case. :)

**Comment by KshitijT** [comment]
It's been a week and the status is not passing - I'll go ahead and merge this PR, but does anyone know why it's taking so long ? Tagging @o-smirnov and @SpheMakh  here, please help.

**Pull request merged**
