### PR TITLE
Minor fixes

### LINKED ISSUE #1241: Obsolete keyword report in flag worker?
https://github.com/caracal-pipeline/caracal/blob/abade14b42c761e16506b8002f442ee5a80ea9d8/caracal/schema/flag_schema.yml#L422-L426

I do not see where this is still being used. The flagging summary is generated anyway if summary is True (which is true by default):

https://github.com/caracal-pipeline/caracal/blob/6021afe0c880d7678869bbc3c515d1f3b59b3119/caracal/workers/flag_worker.py#L507-L527

### PR DESCRIPTION
**Pull request by KshitijT**
As the title suggest, really minor changes.

Fixes #1241 and #1228.

### CODE REVIEW

**Comment by o-smirnov** [comment]
Why remove the "report" option here, @KshitijT? It's universal to all workers.

**Comment by KshitijT** [comment]
> Why remove the "report" option here, @KshitijT? It's universal to all workers.

See #1241 . If it is required, I can amend the PR, but then let's close #1241.

**Comment by o-smirnov** [comment]
Yes, please put it back. :)

**Comment by KshitijT** [comment]
> Yes, please put it back. :)

Done!

**Comment by o-smirnov** [comment]
OK, going to merge this without testing, as it is just a change of message effectively.

**Pull request merged**
