### PR TITLE
Issue 1161 & 1146

### PR DESCRIPTION
**Pull request by o-smirnov**
Commence the tests...

### CODE REVIEW

**Comment by gigjozsa** [comment]
Latest commit merged #1162 into master then master with this one:
This will result in a test without radiopadre (which I will do at home).

**Comment by gigjozsa** [comment]
Test went through in 1h (docker + singularity) on Ray. Jenkins is currently still executing pip to install caracal. @o-smirnov please override waiting test results and merge if you like, I've run the test (including final reports) on Ray.

**Comment by gigjozsa** [comment]
Resolves #1162

**Comment by o-smirnov** [comment]
Hmmm @gigjozsa I appear to have misled you. The ``final_report`` setting was being ignored, so it was invoking radiopadre at the end anyway. I have pushed a change that will make it honour it.

**Comment by o-smirnov** [comment]
Jenkins complaining. Dunno WTF is going on.
```
# ERROR Error downloading https://index.docker.io/v2/osmirnov/radiopadre/blobs/sha256:5edf04faf6f5b82baaf858eb39bd79b0159efb83948c5c42aa293455f25fe874. Do you have permission to write to /var/lib/jenkins/.singularity/docker?
```
I'll run a long test overnight and merge and release tomorrow if successful.

**Pull request merged**
